/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Cap extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='30' height='30' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_2" data-name="图层 2_复制 2">
                    <rect className="cls-1"  fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M17.5,34.93h-2v-9.1q0-3.82.1-4.83a10.48,10.48,0,0,1,.67-3,7.77,7.77,0,0,1,1.59-2.33,8.44,8.44,0,0,1,2.7-1.86,8.46,8.46,0,0,1,6.74,0,8.76,8.76,0,0,1,2.75,1.85,7.15,7.15,0,0,1,1.68,2.49,12,12,0,0,1,.67,3.3q.06.76.06,4.44v9.1h-2v-9.2q0-3.33-.09-4.25a9.86,9.86,0,0,0-.53-2.66A5.83,5.83,0,0,0,28.69,17a6.29,6.29,0,0,0-2.08-1.42A6.44,6.44,0,0,0,24,15a6.51,6.51,0,0,0-2.67.59,6.14,6.14,0,0,0-2.16,1.55A5.54,5.54,0,0,0,18,19.22a12.44,12.44,0,0,0-.44,2.67q0,.79,0,3.84Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Cap;
