/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Lbrace extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='28' height='28' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_6" data-name="图层 2_复制 6">
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M27.84,37.66a6.25,6.25,0,0,1-4.53-1.46,6.22,6.22,0,0,1-1.49-4.62V27.86a3.34,3.34,0,0,0-.67-2.27,2.86,2.86,0,0,0-2.24-.76H18V22.06h.92a4.7,4.7,0,0,0,1.35-.17,2.13,2.13,0,0,0,.91-.52,2,2,0,0,0,.51-.9,4.9,4.9,0,0,0,.15-1.31V16.58a9.22,9.22,0,0,1,.34-2.65,4.39,4.39,0,0,1,2.94-3.05,8.48,8.48,0,0,1,2.73-.39h1.23v2.75h-.92a4.43,4.43,0,0,0-1.27.17A2.34,2.34,0,0,0,25.27,15a4.69,4.69,0,0,0-.22,1.55v2.56a8.31,8.31,0,0,1-.18,1.88,3.55,3.55,0,0,1-.56,1.3,2.58,2.58,0,0,1-1,.81,4.71,4.71,0,0,1-1.38.4,3.15,3.15,0,0,1,2.33,1.22,5.49,5.49,0,0,1,.76,3.22v3.72a4.86,4.86,0,0,0,.22,1.58,2.45,2.45,0,0,0,.63,1,2.36,2.36,0,0,0,1,.54,4.61,4.61,0,0,0,1.27.16h.92v2.75Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Lbrace;
