/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class PlusMinus extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg"  width='32' height='32' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2-2" data-name="图层 2">
                    <rect className="cls-1"   fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M22.48,15.11H23.9v7h7v1.42h-7v7H22.48v-7h-7V22.13h7Zm-7,17.15H30.86v1.45H15.48Z"/>
                </g>
            </g>
        </svg>
    }
}

module.exports = PlusMinus;
