/**
 * An autogenerated component that renders the BACKSPACE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Up2 extends React.Component {
        render (){
            return (
                <svg t="1509352698434" viewBox="0 0 1024 1024" version="1.1"
                     xmlns="http://www.w3.org/2000/svg" p-id="2993" width="22"
                     height="22">
                    <path  fill="#3b3e40"
                        d="M511.034511 62.279439 205.769992 491.203348l203.51002 0L409.280012 957.725574l203.511044 0L612.791056 491.203348l203.51002 0L511.034511 62.279439z"
                        p-id="2994"></path>
                </svg>
            )
        }

}

module.exports = Up2;
