/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Vert extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };
    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='28' height='28' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_8" data-name="图层 2_复制 8">
                    <rect className="cls-1" fill='none'  width="48" height="48"/>
                    <g id="图层_13" data-name="图层 13">
                        <line className="cls-2" fill='none' stroke={this.props.color} strokeMiterlimit='10' strokeWidth='2' x1="24" y1="11.5" x2="24" y2="36.5"/>
                    </g>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Vert;
