/**
 * An autogenerated component that renders the BACKSPACE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Calc = () => {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" width='34' height='34' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制" data-name="图层 2_复制">
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <path className="cls-2"  fill='#3b3e40'
                          d="M24,10.14a13.34,13.34,0,0,1,9.78,4.08A13.34,13.34,0,0,1,37.86,24a13.34,13.34,0,0,1-4.08,9.78A13.34,13.34,0,0,1,24,37.86a13.34,13.34,0,0,1-9.78-4.08A13.34,13.34,0,0,1,10.14,24a13.34,13.34,0,0,1,4.08-9.78A13.34,13.34,0,0,1,24,10.14Zm0,25.91a11.61,11.61,0,0,0,8.51-3.54A11.61,11.61,0,0,0,36.06,24a11.61,11.61,0,0,0-3.54-8.51A11.61,11.61,0,0,0,24,11.94a11.61,11.61,0,0,0-8.51,3.54A11.61,11.61,0,0,0,11.94,24a11.61,11.61,0,0,0,3.54,8.51A11.61,11.61,0,0,0,24,36.06Zm-4.38-4.38V29.58h3.75v-12q-.73.18-3.93,1.17V16.53l6.3-1.74v14.8h3.66v2.09Z"/>
                </g>
            </g>
        </svg>
    )
};

module.exports = Calc;
