/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Cup extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='30' height='30' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制" data-name="图层 2_复制">
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M17.5,22.27q0,3,0,3.84A12.44,12.44,0,0,0,18,28.78a5.54,5.54,0,0,0,1.18,2.1,6.14,6.14,0,0,0,2.16,1.55A6.51,6.51,0,0,0,24,33a6.44,6.44,0,0,0,2.62-.56A6.29,6.29,0,0,0,28.69,31a5.83,5.83,0,0,0,1.2-1.85,9.86,9.86,0,0,0,.53-2.66q.09-.92.09-4.25v-9.2h2v9.1q0,3.68-.06,4.44a12,12,0,0,1-.67,3.3,7.15,7.15,0,0,1-1.68,2.49,8.76,8.76,0,0,1-2.75,1.85,8.46,8.46,0,0,1-6.74,0,8.44,8.44,0,0,1-2.7-1.86A7.77,7.77,0,0,1,16.3,30a10.48,10.48,0,0,1-.67-3q-.1-1-.1-4.83v-9.1h2Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Cup;
