/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Delta extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg"  width='26' height='26' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_10" data-name="图层 2_复制 10">
                    <rect className="cls-1" fill='none'  width="48" height="48"/>
                    <path className="cls-2" fill={this.props.color}  d="M10.14,33.8,24,13,37.88,33.8Zm4.16-1.95H33.72L24,17.31Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Delta;
