/**
 * An autogenerated component that renders the BACKSPACE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Down2 extends React.Component {
    render (){
        return (
            <svg t="1509352715345" className="icon" viewBox="0 0 1024 1024" version="1.1"
                 xmlns="http://www.w3.org/2000/svg" p-id="3377" width="22"
                 height="22">
                <path fill="#3b3e40"
                      d="M511.035534 957.726597l305.264519-428.92391L612.790032 528.802688 612.790032 62.281485 409.278989 62.281485l0 466.522226L205.768969 528.803711 511.035534 957.726597z"
                    p-id="3378"></path>
            </svg>
        )
    }

}

module.exports = Down2;
