/**
 * An autogenerated component that renders the EXP iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Exp extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        //return <svg width="40" height="40" viewBox="0 0 48 48"><g fill="none" fillRule="evenodd"><path fill="none" d="M0 0h48v48H0z"/><path d="M28 16.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997h-6.006c-.55 0-.997-.453-.997-.997v-6.006zM30 18h4v4h-4v-4zM14 21c0-.552.456-1 1.002-1h9.996A1 1 0 0 1 26 21v14c0 .552-.456 1-1.002 1h-9.996A1 1 0 0 1 14 35V21zm2 1h8v12h-8V22z" fill={this.props.color}/></g></svg>;


        return (
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 48 48">

                <g id="图层_2" data-name="图层 2">
                    <g id="图层_3" data-name="图层 3">
                        <rect className="cls-1" fill="none" width="48" height="48"/>
                    </g>
                    <g id="图层_2-2" data-name="图层 2">
                        <rect className="cls-2" fill="none" stroke={this.props.color} strokeMiterlimit="10" strokeWidth="2" x="29.5" y="14.5" width="7" height="7" rx="0.5" ry="0.5"/>
                        <path className="cls-3" stroke={this.props.color} fill={this.props.color} strokeMiterlimit="10" strokeWidth="0.5"
                              d="M15.7,21.16l4.16-.72a11.94,11.94,0,0,1,1.6,3.91,29.09,29.09,0,0,1,1.77-2.42,5.4,5.4,0,0,1,1.32-1.21,2.29,2.29,0,0,1,1.1-.28,1.35,1.35,0,0,1,1,.36,1.32,1.32,0,0,1,.35,1,1.29,1.29,0,0,1-.35.94,1.17,1.17,0,0,1-.88.36,3.32,3.32,0,0,1-.88-.14,3.11,3.11,0,0,0-.69-.14,1.52,1.52,0,0,0-1,.36,7.61,7.61,0,0,0-1.53,2.09,16.78,16.78,0,0,0,1.62,4.37,1,1,0,0,0,.73.47.93.93,0,0,0,.54-.16,6.26,6.26,0,0,0,1.06-1.25l.43.25a8,8,0,0,1-2.05,2.39,2.61,2.61,0,0,1-1.5.54,2.23,2.23,0,0,1-1.27-.34,2.87,2.87,0,0,1-.9-1.11,17.5,17.5,0,0,1-.93-2.46q-1.4,1.78-2.19,2.59a5.21,5.21,0,0,1-1.32,1.07,2.57,2.57,0,0,1-1.12.25,1.34,1.34,0,0,1-1-.36,1.25,1.25,0,0,1-.36-.93,1.35,1.35,0,0,1,1.4-1.4,1.75,1.75,0,0,1,.73.19,2.37,2.37,0,0,0,.86.29,1.32,1.32,0,0,0,.62-.14,3.59,3.59,0,0,0,.91-.78q.33-.37,1.23-1.57a19.89,19.89,0,0,0-1.79-5.08,1.24,1.24,0,0,0-1-.54,4,4,0,0,0-.79.1Z"/>
                    </g>
                </g>
            </svg>
        )

    }
}

module.exports = Exp;
