/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Lbracket extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };
    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='26' height='26' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_3" data-name="图层 2_复制 3">
                    <rect className="cls-1"  fill='none' width="48" height="48"/>
                    <path className="cls-2" fill={this.props.color} d="M20.22,37.66V10.48h7.7v2.78H23.52V34.87h4.41v2.78Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Lbracket;
