/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Phi extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg"  width='28' height='28' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_9" data-name="图层 2_复制 9">
                    <rect className="cls-1"  fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M25.1,18.09A9.36,9.36,0,0,1,31,20.39a6.45,6.45,0,0,1,1.55,7.17,7.21,7.21,0,0,1-1.28,2.07,7.45,7.45,0,0,1-1.77,1.46,8.36,8.36,0,0,1-2.15.89,15.75,15.75,0,0,1-2.29.34v6.06H22.92V32.31a10.1,10.1,0,0,1-4.77-1.39A6.38,6.38,0,0,1,15,25.25a6.5,6.5,0,0,1,.49-2.58,6.63,6.63,0,0,1,1.32-2,7.73,7.73,0,0,1,1.82-1.41,8.56,8.56,0,0,1,2.1-.83,15,15,0,0,1,2.23-.34v-7H25.1ZM22.92,19a6,6,0,0,0-2,.64,4.85,4.85,0,0,0-1.79,1.88,6.9,6.9,0,0,0-.67,3.32,8,8,0,0,0,.79,3.79,5.81,5.81,0,0,0,2,2.22,5.07,5.07,0,0,0,1.68.62ZM25.1,31.45A5.77,5.77,0,0,0,27,30.86a4.85,4.85,0,0,0,1.88-1.95,7.47,7.47,0,0,0,.66-3.47A8.76,8.76,0,0,0,28.89,22a5,5,0,0,0-1.68-2.18A6.24,6.24,0,0,0,25.1,19Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Phi;
