/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Pi extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='36' height='36' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_8" data-name="图层 2_复制 8">
                    <rect className="cls-1"  fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M32.44,18.45v2.14H27.91L27.52,25q-.12,1.16-.12,2,0,2,.63,2.48a2.6,2.6,0,0,0,1.53.45A2,2,0,0,0,31.8,28.2h.7q-.64,4.07-4.34,4.07a4.46,4.46,0,0,1-2.76-.79,2.75,2.75,0,0,1-1-2.34q0-1,.41-4.34l.53-4.22H21.15a56.86,56.86,0,0,1-1,7.79,7.45,7.45,0,0,1-1.27,3.18,2.5,2.5,0,0,1-1.89.72,2.74,2.74,0,0,1-1.51-.4,1.19,1.19,0,0,1-.62-1q0-.62,1.06-1.68a11.19,11.19,0,0,0,2.31-3.23,18.66,18.66,0,0,0,1.15-5.34H18.06a4.63,4.63,0,0,0-2.45.53A6.27,6.27,0,0,0,14,22.65h-.7a7.85,7.85,0,0,1,1.47-2.58,4.33,4.33,0,0,1,1.85-1.32A12.47,12.47,0,0,1,20,18.45Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Pi;
