/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Rbrace extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };
    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='28' height='28'  viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_2_复制_5" data-name="图层 2_复制 5">
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <path className="cls-2"
                          fill={this.props.color}
                          d="M20.16,10.48a6.27,6.27,0,0,1,4.54,1.46q1.49,1.46,1.49,4.64V19a3.33,3.33,0,0,0,.67,2.26,2.85,2.85,0,0,0,2.23.75H30v2.77H29.1a4.7,4.7,0,0,0-1.35.17,1.93,1.93,0,0,0-1.4,1.42,5,5,0,0,0-.15,1.31v3.85a9.15,9.15,0,0,1-.34,2.64,4.39,4.39,0,0,1-3,3,8.58,8.58,0,0,1-2.74.39H18.93V34.9h.94a4.61,4.61,0,0,0,1.27-.16,2.33,2.33,0,0,0,1-.55,2.52,2.52,0,0,0,.63-1A4.68,4.68,0,0,0,23,31.64V27.83a8.39,8.39,0,0,1,.18-1.88,3.63,3.63,0,0,1,.56-1.3,2.46,2.46,0,0,1,1-.8,4.86,4.86,0,0,1,1.38-.4,3.17,3.17,0,0,1-2.32-1.24A5.53,5.53,0,0,1,23,19V16.55A4.93,4.93,0,0,0,22.74,15a2.45,2.45,0,0,0-.63-1,2.36,2.36,0,0,0-1-.54,4.61,4.61,0,0,0-1.27-.16h-.94V10.48Z"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Rbrace;
