/**
 * An autogenerated component that renders the BACKSPACE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
class Right2 extends React.Component {
    render (){
        return (
            <svg t="1509352707049" className="icon" viewBox="0 0 1024 1024" version="1.1"
                 xmlns="http://www.w3.org/2000/svg" p-id="3121" width="22"
                height="22">

                <path fill="#3b3e40"
                    d="M958.759625 510.002506 529.835715 204.736964l0 203.51002L63.312466 408.246985l0 203.51002 466.522226 0 0 203.51002L958.759625 510.002506z"
                    p-id="3122"></path>
            </svg>
        )
    }
}

module.exports = Right2;
