/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const PropTypes = require('prop-types');

class Subscript extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return <svg xmlns="http://www.w3.org/2000/svg" width='40' height='40' viewBox="0 0 48 48">
            <g id="图层_2" data-name="图层 2">
                <g id="图层_3" data-name="图层 3">
                    <rect className="cls-1" fill='none' width="48" height="48"/>
                    <rect className="cls-2" fill='none' stroke={this.props.color} strokeMiterlimit='10' strokeWidth='2' x="15" y="17.18" width="10" height="13.64" rx="0.5" ry="0.5"/>
                    <rect className="cls-2" fill='none' stroke={this.props.color} strokeMiterlimit='10' strokeWidth='2' x="29" y="30" width="6" height="6" rx="0.5" ry="0.5"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Subscript;
