/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
const Iconography = require('../iconography');


class WordButton extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            ClassName: 'word-button',
            ClassName2:'word-button word-button-on-touch',
            active:!1
        }
    }

    onTouchStart = () => {
        if(this.props.value!=='shift'){
            this.setState({active:!0});
        }

    };
    onTouchEnd = (e) => {
        if(this.props.value==='shift'){
            this.setState({active:!this.state.active});
        }else{
            this.setState({active:!1});
        }
        this.props.handleExtraClick(this.props.value);
        e.preventDefault();
    };

    render() {

        let a =  this.props.value;
        const SvgForName = Iconography[a.toUpperCase()];
        if(SvgForName){
            a =  <SvgForName />
        }

        return (
            <div className={(this.state.active?this.state.ClassName2:this.state.ClassName) + ' mathboard_'+this.props.value} onTouchStart={() => this.onTouchStart()} onTouchEnd={(e) => this.onTouchEnd(e)}>
                {a}
            </div>
        )
    }
}

module.exports =  WordButton;
